version: '3'

services:
  spring-demo:
    build:
      context: .
      dockerfile: docker/spring/Dockerfile
    container_name: spring-demo # コンテナ名を指定
    environment: # 環境変数を設定
      - SPRING_PROFILES_ACTIVE=dev
    tty: true # コンテナを終了させないために設定
    working_dir: /app # 作業ディレクトリを指定
    volumes: # マッピングを指定
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./gradle:/app/gradle
      - ./settings.gradle:/app/settings.gradle
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 8080:8080 # 実行用
      - 5005:5005 # デバッグ用
