select
    ORDERS.ID,
    ORDERS.ORDER_DATE,
    ORDERS.TOTAL_AMOUNT,
    PRODUCTS.NAME,
    PRODUCTS.PRICE,
    ORDER_ITEMS.QUANTITY,
    ORDER_ITEMS.SUB_TOTAL_AMOUNT
from ORDERS
inner join ORDER_ITEMS on
    ORDERS.ID = ORDER_ITEMS.ORDER_ID
inner join PRODUCTS on
    ORDER_ITEMS.PRODUCT_ID = PRODUCTS.ID;


