SELECT
    ORDERS.ID,
    ORDERS.ORDER_DATE,
    ORDERS.TOTAL_AMOUNT,
    PRODUCTS.NAME AS PRODUCT_NAME,
    PRODUCTS.PRICE AS PRODUCT_PRICE,
    ORDER_ITEMS.QUANTITY,
    ORDER_ITEMS.SUB_TOTAL_AMOUNT
FROM ORDERS
    INNER JOIN ORDER_ITEMS ON ORDERS.ID = ORDER_ITEMS.ORDER_ID
    INNER JOIN PRODUCTS ON ORDER_ITEMS.PRODUCT_ID = PRODUCTS.ID
WHERE ORDERS.ID = :orderId