version: '3'

services:
  mssql-demo:
    build:
      context: ..
      dockerfile: docker/mssql/Dockerfile
    user: root # ルートユーザーで実行
    container_name: mssql-demo # コンテナ名を指定
    environment: # 環境変数を設定
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
      - MSSQL_LCID=${MSSQL_LCID}
      - TZ=${TZ}
      - MSSQL_COLLATION=${MSSQL_COLLATION}
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 1433:1433
    volumes: # マッピングを指定
      - mssql_data:/var/opt/mssql/data # dataの永続化
      - mssql_log:/var/opt/mssql/log # logの永続化
      - mssql_secrets:/var/opt/mssql/secrets # secretsの永続化
  spring-demo:
    build:
      context: ..
      dockerfile: docker/spring/Dockerfile
    container_name: spring-demo # コンテナ名を指定
    environment: # 環境変数を設定
      - SPRING_PROFILES_ACTIVE=dev
    tty: true # コンテナを終了させないために設定
    working_dir: /app # 作業ディレクトリを指定
    volumes: # マッピングを指定
      - ../src:/app/src
      - ../build.gradle:/app/build.gradle
      - ../gradlew:/app/gradlew
      - ../gradle:/app/gradle
      - ../settings.gradle:/app/settings.gradle
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 8080:8080 # 実行用
      - 5005:5005 # デバッグ用
    depends_on: # mssqlコンテナ起動後にspringコンテナを起動
      - mssql-demo
volumes:
  mssql_data:
  mssql_log:
  mssql_secrets: