
CREATE TABLE TASKS
(
    ID         BIGINT PRIMARY KEY IDENTITY(1,1),
    TITLE      VARCHAR(255),
    CONTENT    TEXT,
    STATUS     INT NOT NULL,
    CREATED_AT DATETIME
);

CREATE TABLE SUB_TASKS
(
    ID         BIGINT PRIMARY KEY IDENTITY(1,1),
    PARENT_ID  BIGINT,
    TITLE      VARCHAR(255),
    CONTENT    TEXT,
    STATUS     INT NOT NULL,
    CREATED_AT DATETIME,
    FOREIGN KEY (PARENT_ID) REFERENCES TASKS (ID)
);

CREATE TABLE APP_USERS
(
    ID    BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME  VARCHAR(255),
    EMAIL VARCHAR(255)
);

CREATE TABLE PRODUCTS
(
    ID    BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME  VARCHAR(255),
    PRICE DECIMAL
);

CREATE TABLE ORDERS
(
    ID           BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID      BIGINT,
    ORDER_DATE   DATE,
    TOTAL_AMOUNT DECIMAL,
    VERSION      BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES APP_USERS (ID)
);

CREATE TABLE ORDER_ITEMS
(
    ID               BIGINT PRIMARY KEY IDENTITY(1,1),
    ORDER_ID         BIGINT,
    SEQ_NO           INT,
    PRODUCT_ID       BIGINT,
    QUANTITY         INT,
    SUB_TOTAL_AMOUNT DECIMAL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);